services:
  - type: web
    name: email-agent-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: SECRET_KEY
        value: GEMINI_API_KEY
    autoDeploy: true
    branch: main

  - type: web
    name: email-agent-frontend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run steamlit_app.py --server.port 10000 
    envVars:
      - key: BACKEND_URL
        value: https://email-agent-backend.onrender.com
    autoDeploy: true
    branch: main
